/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.postgres;

import org.junit.jupiter.api.Test;

import java.sql.SQLException;

import static org.junit.jupiter.api.Assertions.*;

class CustomPostgreSQLProcedureTest {
    @Test void someLibraryMethodReturnsTrue() throws SQLException {
        CustomPostgreSQLProcedure classUnderTest = new CustomPostgreSQLProcedure();
    }
}
