/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.postgres;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class CustomPostgreSQLProcedureTest {
    @Test void someLibraryMethodReturnsTrue() {
        CustomPostgreSQLProcedure classUnderTest = new CustomPostgreSQLProcedure();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
